application: site-alive-checker
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: latest

handlers:
- url: /css
  static_dir: static/css
- url: /img
  static_dir: static/img
- url: /js
  static_dir: static/js
#- url: /.*
#  script: myapp.app
#- url: /checksiteforever.*
#  script: site_alive_checker.app
#  login: admin
#  secure: always
- url: /.*
  script: main.app
  login: admin
  secure: always
